version: "3.9"

services:
  postgres:
    image: postgres:12.7-alpine3.14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_ADMIN_USER
      POSTGRES_PASSWORD: $POSTGRES_ADMIN_PASSWORD
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/data/postgres

    network_mode: bridge
    ports:
      - "5432:5432"

volumes:
  postgres_data:
